---
title: "03_Visualization"
author: "Sachida Pokhrel"
date: "2025-02-19"
output: html_document
---

```{r}
#load libraries
library(tidyverse)
library(ggpubr)
library(ggrepel) #useful for labeling points
library(ggplot2)

#color consistency and assessibility for variables along different plots makes it easier to understand

cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

sample.data.bac <- read.csv("BacterialAlpha.csv", na.strings = "na")
sample.data.bac

#making variable into categorical
sample.data.bac$Time_Point <- as.factor(sample.data.bac$Time_Point)
sample.data.bac$Crop <- as.factor(sample.data.bac$Crop)

#by changing the factor level, we can change the way ggplot plots the data
sample.data.bac$Crop <- factor(sample.data.bac$Crop, levels = c("Soil", "Cotton", "Soybean"))

#plot 1-B
bac.even <- ggplot(sample.data.bac, aes(x = Time_Point, y = even, color = Crop)) +
  geom_boxplot(position = position_dodge()) +
  geom_point(position = position_jitterdodge(0.05)) +
  xlab("Time") +
  ylab("Pielou's evenness") +
  scale_color_manual(values = cbbPalette)+
  theme_classic()
bac.even

# Plot 2-A
sample.data.bac.no.soil <- subset(sample.data.bac, Crop != "Soil") #subset the file without soil data; != means not equal to

water.imbibed <- ggplot(sample.data.bac.no.soil, aes(Time_Point, 1000 * Water_Imbibed, color = Crop)) +  # Define aesthetics: x-axis as Time.Point, y-axis as Water_Imbibed (converted to mg), and color by Crop
  geom_jitter(width = 0.5, alpha = 0.5) +  # Add jittered points to show individual data points with some transparency
  stat_summary(fun = mean, geom = "line", aes(group = Crop)) +  # Add lines representing the mean value for each Crop group
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.5) +  # Add error bars representing the standard error of the mean
  xlab("Hours post sowing") +  # Label the x-axis
  ylab("Water Imbibed (mg)") +  # Label the y-axis
  scale_color_manual(values = c(cbbPalette[[2]], cbbPalette[[3]]), name = "", labels = c("", "")) +  # Manually set colors for the Crop variable
  theme_classic() +  # Use a classic theme for the plot
  theme(strip.background = element_blank(), legend.position = "none") +  # Customize theme: remove strip background and remove the legends
  facet_wrap(~Crop, scales = "free")  # Create separate panels for each Crop, allowing free scales
water.imbibed

#Plot 3- C
water.imbibed.cor <- ggplot(sample.data.bac.no.soil, aes(y = even, x = 1000 * Water_Imbibed, color = Crop)) +  # Define aesthetics: y-axis as even, x-axis as Water_Imbibed (converted to mg), and color by Crop
  geom_point(aes(shape = Time_Point)) +  # Add points with different shapes based on Time.Point
  geom_smooth(se = FALSE, method = lm) +  # Add a linear model smooth line (trend line) without confidence interval shading
  xlab("Water Imbibed (mg)") +  # Label the x-axis
  ylab("Pielou's evenness") +  # Label the y-axis
  scale_color_manual(values = c(cbbPalette[[2]], cbbPalette[[3]]), name = "", labels = c("Cotton", "Soybean")) +  # Manually set colors for the Crop variable
  scale_shape_manual(values = c(15, 16, 17, 18), name = "", labels = c("0 hrs", "6 hrs", "12 hrs", "18 hrs")) +  # Manually set shapes for the Time.Point variable
  theme_classic() +  # Use a classic theme for the plot
  guides(color = "none")+ #removes the color legend
  theme(strip.background = element_blank(), legend.position = "none") +
  facet_wrap(~Crop, scales = "free")  # Create separate panels for each Crop, allowing free scales
water.imbibed.cor

figure2 <- ggarrange(#use ggarrange to arrange all the figures together
  water.imbibed,
  bac.even,
  water.imbibed.cor,
  labels = "auto",
  nrow = 3, #number of rows for the figure
  ncol= 1, #number of columns for figure
  legend = FALSE
)
figure2

```
###integrating statistics into the plots for exploratory analyses

```{r}
#ggpubr integrate stats with actual plot itself
#anova type designs
bac.even +
  stat_compare_means(method = "anova") #provides anova inferences to the variable
#more exploratory so p-value are not adjusted, using proper stats is important
bac.even +
  geom_pwc(aes(group = Crop, method = "t.test", label = "p.adj.format")) #display adjusted p-value and do the pairwise comparison test using t-test on the different crops.

bac.even +
  geom_pwc(aes(group = Time_Point), method = "t.test", label = "{p.adj.format}.{p.adj.signif}")
#display adjusted p-value and significance for Time_point as group
water.imbibed.cor +
#stat_cor() + #display correlation Pearson's in default, have to change if we want Spearman's correlation
  stat_regline_equation() #display equation for the regression line
```

##plot fold change

```{r}
diff.abund <- read.csv("diff_abund.csv", na.strings = "na")
str(diff.abund) #structure of the file
diff.abund$log10_pvalue <- -log10(diff.abund$p_CropSoybean) #negative log fold change for p-value
diff.abund.label <- diff.abund[diff.abund$log10_pvalue > 30,] #separate out the most abundant one according to the log10 p-value greater than 30.

ggplot()+
  geom_point(data = diff.abund, aes(x=lfc_CropSoybean, y = log10_pvalue, color = diff_CropSoybean))+
   geom_point(data = diff.abund.label, aes(x=lfc_CropSoybean, y = log10_pvalue, color = diff_CropSoybean),shape = 17, color = "red", size = 4)+ 
  theme_classic() +
  geom_text_repel(data = diff.abund.label, aes(x= lfc_CropSoybean, y = log10_pvalue, color = diff_CropSoybean, label = Label), color = "red")+ #text_repel automatically adjusts the position of text labels to prevent overlap with other labels and data points
  scale_color_manual(values = cbbPalette, name = "Significant")+
  xlab("log fold change soil vs. soybean")+
  ylab("log10 p-value")

#focus on what you want to emphasis in the plot, what's your story that you want to tell from the plot. Don't overdo it. Keep it simple and understandable

```

