---
title: "InClass_Cloding_Assignment"
author: "Sachida Pokhrel"
date: "2025-02-06"
output: pdf_document
---

#functions
```{r}
#make a vector 
z <- c(1:200) 

#calculate mean 
mean(z)

#calculate standard deviation
sd(z)

#make a new logical dataset of the vector z
zlog <- z>30

#make dataframe for z and zlog
zdf <- data.frame(z, zlog)

#define column names for the columns of the dataframe, zdf
colnames(zdf) <- c("zvec", "zlogic")

#generating a squared zvec in a new column
zdf$zsquared <- ((zdf$zvec)^2)

#subsetting the zsquared for greater than 10 and less than 100
zdf$zsquared[(zdf$zsquared>10)&(zdf$zsquared<100)]

#using subset function
subset(zdf, (zsquared > 10)&(zsquared < 100))

#taking 26th row
zdf [26,]

#taking zsquared value for 180th column
zdf [180,3]

```
#reading data into R
```{r}
datum1 <-read.csv("C:/Users/pokhr/OneDrive - Auburn University/Reproducibility/TipsR.csv")
datum2 <-read.csv("C:/Users/pokhr/OneDrive - Auburn University/Reproducibility/TipsR.csv", na.strings = ".")
```

